### PR TITLE
Declare Rake as a Runtime Dependency

### LINKED ISSUE #18: Require gem `rake` but no dependency
```
$ bundle install
....
    Installing digest-crc 0.6.0 (was 0.5.1) with native extensions
    Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
    
    current directory:
    /Users/guoqi/.bundle/vendor/ruby/2.5.0/gems/digest-crc-0.6.0/ext/digest
    rake
    RUBYARCHDIR=/Users/guoqi/.bundle/vendor/ruby/2.5.0/extensions/x86_64-darwin-18/2.5.0/digest-crc-0.6.0
    RUBYLIBDIR=/Users/guoqi/.bundle/vendor/ruby/2.5.0/extensions/x86_64-darwin-18/2.5.0/digest-crc-0.6.0
    /Users/guoqi/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems.rb:289:in
    `find_spec_for_exe': can't find gem rake (>= 0.a) with executable rake
    (Gem::GemNotFoundException)
    from
    /Users/guoqi/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems.rb:308:in
    `activate_bin_path'
    	from /Users/guoqi/.rvm/gems/ruby-2.5.0@global/bin/rake:23:in `<main>'
    	from /Users/guoqi/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:24:in `eval'
    	from /Users/guoqi/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:24:in `<main>'
```
There is not `rake` gem in my mac and my project. I think that should add a dependency in gemspec?

### LINKED ISSUE #19: Getting error when importing digest-crc as a Fastlane dependency
```
Fetching digest-crc 0.6.0 (was 0.4.1)
Installing digest-crc 0.6.0 (was 0.4.1) with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
```

This error only happens on 0.6.0, which was released today. Didn't happen with older versions.

### PR DESCRIPTION
**Pull request by rogerluan**
Resolves #18 
Resolves #19

### CODE REVIEW

**Comment by postmodern** [comment]
@rogerluan thank you, 0.6.1 has been pushed. I do worry that by making rake ~> 13.0 a runtime dependency, it will be activated whenever digest-crc is activated. Not sure what weird side-effects this might have in certain environments or projects where rake isn't normally loaded.

**Comment by rogerluan** [comment]
Good point, I didn't think about that. Do you think it's worth removing the version specifier?

**Comment by postmodern** [comment]
I seem to remember that removing the version qualifier actually slows down dependency resolution.

**Comment by rogerluan** [comment]
Alright, well, if someone open a related issue, we'll know where to investigate 😁 
Cheers!

**Pull request merged**
